version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    command: >
      sh -c "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"

