name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify syntax by compiling all Python files
        run: python -m compileall .

      - name: Create data directory (if missing)
        run: |
          mkdir -p data
          chmod 777 data

      - name: Run database initialization
        run: python init_db.py

      - name: Run a quick import test of FastAPI app
        run: |
          python - << 'PYCODE'
          import os
          from fastapi import FastAPI
          from main import app
          print("FastAPI app imported successfully.")
          PYCODE

      - name: Smoke-test endpoint (UVicorn + curl)
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8001 --workers 1 --lifespan on > uvicorn.log 2>&1 &
          UVICORN_PID=$!
          for i in {1..15}; do
            if curl -s http://127.0.0.1:8001/docs > /dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 1
          done
          if ! curl -s http://127.0.0.1:8001/docs > /dev/null; then
            echo "❌ Could not reach /docs endpoint"
            exit 1
          fi
          kill $UVICORN_PID

      - name: Report success
        run: echo "✅ Build and verification completed successfully."
